targets = ["//:numeric_conversion"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
version = "1.34.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.34.1"