manifest = "15bf9255cb0a263c604a32824b88867f579809142f12375cd50d258cf2c14381"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.41.0" ]
revision = "c32805df725494aca225f78f2d64b24bdf99e56a"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.41.0" ]
revision = "3dd65e69f2a9ed5bfc98d36329c9e832a650cf2b"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.41.0" ]
revision = "820cdd0df618d97b19e6583507b03320724cc35f"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.41.0" ]
revision = "c848776c45974808d87763367162d9ab445c323e"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.41.0" ]
revision = "27473651c329bf6c2218c6899279776ffb3783a7"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.41.0" ]
revision = "231c5eb4d0a10b0daa8950d2c91a07e2bfda5a2d"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.41.0" ]
revision = "6ee28fd8eeec0d2989d6c74f56027fbede584d06"
