targets = ["//:numeric_conversion"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.58.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.58.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.58.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
version = "1.58.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
version = "1.58.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "1.58.0"